contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #getstructures channel"
    url: https://nfcore.slack.com/channels/getstructures
    about: Discussion about the nf-core/getstructures pipeline
